settings:
  title: 'Status'
  url: 'https://status-production.demiart.workers.dev/' # used for Slack messages
  logo: logo.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-sexlikereal-com # unique identifier
    name: www.sexlikereal.com
    # description: 'You write code. They handle the rest.' # default=empty
    url: 'https://www.sexlikereal.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: www-sexlikereal-jp # unique identifier
    name: www.sexlikereal.jp
    # description: 'You write code. They handle the rest.' # default=empty
    url: 'https://www.sexlikereal.jp/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: deovr-com # unique identifier
    name: deovr.com
    # description: 'You write code. They handle the rest.' # default=empty
    url: 'https://deovr.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
